version: '3'

services: 
  mongo:
    image: mongo
    volumes: 
      - 'mongodata:/data/db'
    ports: 
    - '28000:27017'
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
      - MONGO_INITDB_DATABASE=BlogDb
  blogserver:
    image: ketrag/blogapi
    ports: 
      - '84:8000'
  blogui:
    image: ketrag/blogui
    ports: 
        - '3001:3000'

volumes: 
  mongodata:
    